apiVersion: v1
kind: Secret
metadata:
    name: gitlab-secret
    namespace: external-secrets
    labels:
        type: gitlab
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:hfFs5q3wJiYQWzj7pz4CgjLrUbfM3Fo0gis=,iv:Hcp26BLq1eR3LDyJ5zSRcC+jljyGe4elVaQB+g/Nc5E=,tag:Tf2ZnR23bgROk5OckxVtEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-18T06:36:54Z"
    mac: ENC[AES256_GCM,data:iML7yvyPveHKyYHyJ1ORmSl+uywXtTTcrhxSPaFydcD3og+GajRgqivwTQbf734KrP0LkDqrryV+3TLQMHN04TVpPg0OlgZXfJ+tWoquVLoHqDehmZc5/6vsuWnza+zAxT4a3QLxW2JpQLYADgFjnb4iEDaPYNP+73YPGkE83sc=,iv:1cLxYlyYGitsXwh6gOujbUfgkIhyPHIlZjDdSBcm8Nk=,tag:cLO5SjEMdmYtis+1yIx1zA==,type:str]
    pgp:
        - created_at: "2022-06-18T06:36:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1PDY17aMF/BAQf/emrl1+m6YAVNtz5mAOzGxO93aCEKx45QFV0egul0EHTz
            HV4iVszIT4YFD3zcexk9zHLUrkJoIt5u51Ic2AjvYUN82Lrfz80n6e3nTKaucPak
            B1s4W4IVI4CdqbAWTh/Gn0o/gfgtnK1Kpws2IuztOJSM1SDYZQ718Pg2AGiqCM1N
            IiFxpWEjUT8+h/XerIlbFurDxHxS8j5AOQbvqyJfdkLqZAvprwXNaoe/lloQ3+1L
            ozonQ7SWF+rQhsgNGV04H218tnWhB2f2TWVHjnPlxQHiKjtG1I5lOTOHpHtpraq4
            oJ3ShfrwbLRc7wESIsyTfM2jIinHMRdesuEjcsoB7NJeAb5J9wMh2Sxr6+txvfH+
            MY9R1wtjyF6zya82wVegbaseFhZcLmuf3POn/ThZu/u4dmqif+FtxRakQW2CyJAy
            8NDd7fVljxJ80tvQ0S6y967eEgTjYDSdSZVbvjoJew==
            =5FAx
            -----END PGP MESSAGE-----
          fp: B956F8F04205E68DB4798D853B9FD16889B70FBE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
